package com.adapty.kmp.internal.plugin.constants

internal enum class AdaptyPluginMethod(val methodName: String) {
    ACTIVATE("activate"),
    IDENTIFY("identify"),
    GET_PROFILE("get_profile"),
    UPDATE_PROFILE("update_profile"),
    LOGOUT("logout"),
    SET_INTEGRATION_IDENTIFIER("set_integration_identifiers"),
    GET_PAYWALL("get_paywall"),
    GET_PAYWALL_PRODUCTS("get_paywall_products"),
    LOG_SHOW_PAYWALL("log_show_paywall"),
    LOG_SHOW_ONBOARDING("log_show_onboarding"),
    GET_PAYWALL_FOR_DEFAULT_AUDIENCE("get_paywall_for_default_audience"),
    UPDATE_ATTRIBUTION("update_attribution_data"),
    RESTORE_PURCHASES("restore_purchases"),
    MAKE_PURCHASE("make_purchase"),
    REPORT_TRANSACTION("report_transaction"),
    IS_ACTIVATED("is_activated"),
    SET_LOG_LEVEL("set_log_level"),
    SET_FALLBACK_PAYWALLS("set_fallback_paywalls"),
    PRESENT_CODE_REDEMPTION_SHEET("present_code_redemption_sheet"),
    UPDATE_COLLECTING_REFUND_DATA_CONSENT("update_collecting_refund_data_consent"),
    UPDATE_REFUND_PREFERENCE("update_refund_preference"),
    CREATE_WEB_PAYWALL_URL("create_web_paywall_url"),
    OPEN_WEB_PAYWALL("open_web_paywall"),
    CREATE_VIEW("adapty_ui_create_view"),
    PRESENT_VIEW("adapty_ui_present_view"),
    DISMISS_VIEW("adapty_ui_dismiss_view"),
    SHOW_DIALOG("adapty_ui_show_dialog"),
}