package com.adapty.kmp.internal.plugin.constants

internal enum class AdaptyPluginMethod(val methodName: String) {
    ACTIVATE("activate"),
    IDENTIFY("identify"),
    GET_PROFILE("get_profile"),
    GET_CURRENT_INSTALLATION_STATUS("get_current_installation_status"),

    UPDATE_PROFILE("update_profile"),
    LOGOUT("logout"),
    SET_INTEGRATION_IDENTIFIER("set_integration_identifiers"),
    GET_FLOW("get_flow"),
    GET_ONBOARDING("get_onboarding"),
    GET_ONBOARDING_FOR_DEFAULT_AUDIENCE("get_onboarding_for_default_audience"),
    GET_PAYWALL_PRODUCTS("get_paywall_products"),
    LOG_SHOW_FLOW("log_show_flow"),
    GET_FLOW_FOR_DEFAULT_AUDIENCE("get_flow_for_default_audience"),
    UPDATE_EXTERNAL_ATTRIBUTION("update_external_attribution_data"),
    RESTORE_PURCHASES("restore_purchases"),
    MAKE_PURCHASE("make_purchase"),
    MAKE_PROMOTED_PURCHASE("make_promoted_purchase"),
    REPORT_TRANSACTION("report_transaction"),
    IS_ACTIVATED("is_activated"),
    SET_LOG_LEVEL("set_log_level"),
    SET_FALLBACK("set_fallback"),
    PRESENT_CODE_REDEMPTION_SHEET("present_code_redemption_sheet"),
    UPDATE_COLLECTING_REFUND_DATA_CONSENT("update_collecting_refund_data_consent"),
    UPDATE_REFUND_PREFERENCE("update_refund_preference"),
    CREATE_WEB_PAYWALL_URL("create_web_paywall_url"),
    OPEN_WEB_PAYWALL("open_web_paywall"),
    CREATE_FLOW_VIEW("adapty_ui_create_flow_view"),
    PRESENT_FLOW_VIEW("adapty_ui_present_flow_view"),
    DISMISS_FLOW_VIEW("adapty_ui_dismiss_flow_view"),
    SHOW_DIALOG("adapty_ui_show_dialog"),


    OPEN_URL("adapty_ui_open_url"),
    REQUEST_APP_REVIEW("adapty_ui_request_app_review"),
    FLOW_VIEW_DID_ANSWER_PERMISSION("flow_view_did_answer_permission"),
    OBSERVER_PURCHASE_DID_START("observer_purchase_did_start"),
    OBSERVER_PURCHASE_DID_FINISH("observer_purchase_did_finish"),
    OBSERVER_RESTORE_DID_START("observer_restore_did_start"),
    OBSERVER_RESTORE_DID_FINISH("observer_restore_did_finish"),

    CREATE_ONBOARDING_VIEW("adapty_ui_create_onboarding_view"),
    PRESENT_ONBOARDING_VIEW("adapty_ui_present_onboarding_view"),
    DISMISS_ONBOARDING_VIEW("adapty_ui_dismiss_onboarding_view"),
}